// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjcy6Dn5lCbuqtKjtbcy69-2OcJD2MHvI',
    appId: '1:306733756321:web:9e06cc759a4bdf69fee5e0',
    messagingSenderId: '306733756321',
    projectId: 'haniwon-fd366',
    authDomain: 'haniwon-fd366.firebaseapp.com',
    storageBucket: 'haniwon-fd366.firebasestorage.app',
    measurementId: 'G-WVDHZL5J9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjcy6Dn5lCbuqtKjtbcy69-2OcJD2MHvI',
    appId: '1:306733756321:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '306733756321',
    projectId: 'haniwon-fd366',
    storageBucket: 'haniwon-fd366.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjcy6Dn5lCbuqtKjtbcy69-2OcJD2MHvI',
    appId: '1:306733756321:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '306733756321',
    projectId: 'haniwon-fd366',
    storageBucket: 'haniwon-fd366.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppV2',
  );
}
